export { default as CTAContent } from "./ctaContent";
export { default as CTAContentButton } from "./ctaContentButton";
export { default as TextImage } from "./textImg";
export { default as TextImage2 } from "./textImg2";
export { default as Contact } from "./contact";
export { default as PortableTextView } from "./portableText";
export { default as PortableTextEvent } from "./portableTextEvent";
export { default as RegularText } from "./regularText";
export { default as AnmeldeContent } from "./anmeldeContent";
